EXTRA_LIBS=-lopencv_features2d -lopencv_imgproc -lopencv_imgcodecs -lopencv_core -lopencv_hal
EXTRA_SOURCES=extractor.cpp
EXTRA_C_SOURCES=generic.c host.c imop.c mathop.c sift.c

DONKEY_HOME=../..
include $(DONKEY_HOME)/src/Makefile.common

