#!/bin/bash

echo heehaw


PLUGIN=$1
PROTOCOL=$2

if [ -z "$PLUGIN" ]
then
	echo usage:
	echo './heehaw <plugin> [protocol]'
	echo 'plugin: qbic'
	echo 'protocol: thrift (default), grpc'
	exit 1
fi

if [ -z "$PROTOCOL" ]
then
	PROTOCOL=thrift
fi

PLUGIN_DIR=plugins/$PLUGIN

if [ ! -d plugins/$PLUGIN ]
then
	echo Plugin $PLUGIN does not exist.
	exit 2
fi


if [ ! -f $PLUGIN_DIR/config.sh ]
then
	echo Missing $PLUGIN_DIR/config.sh
	exit 3
fi

. plugins/$PLUGIN/config.sh

rm -f src/Makefile.protocol.inc
if [ "$PROTOCOL" = http ]
then
	ln -s Makefile.http.inc src/Makefile.protocol.inc
elif [ "$PROTOCOL" = grpc ]
then
	ln -s Makefile.grpc.inc src/Makefile.protocol.inc
elif [ "$PROTOCOL" = thrift ]
then
	ln -s Makefile.thrift.inc src/Makefile.protocol.inc
else
	echo PROTOCOL should be http or grpc or thrift
	exit 5
fi

rm -rf src/plugin
ln -s $PWD/$PLUGIN_DIR src/plugin

pushd src
make 
popd


