#!/bin/bash

echo heehaw


PLUGIN=$1

if [ -z "$PLUGIN" ]
then
	echo please provide a plugin name
	exit 1
fi

PLUGIN_DIR=plugins/$PLUGIN

if [ ! -d plugins/$PLUGIN ]
then
	echo Plugin $PLUGIN does not exist.
	exit 2
fi


if [ ! -f $PLUGIN_DIR/config.sh ]
then
	echo Missing $PLUGIN_DIR/config.sh
	exit 3
fi

. plugins/$PLUGIN/config.sh

rm -f src/Makefile.protocol.inc
if [ "$PROTOCOL" = http ]
then
	ln -s Makefile.http.inc src/Makefile.protocol.inc
elif [ "$PROTOCOL" = grpc ]
then
	ln -s Makefile.grpc.inc src/Makefile.protocol.inc
elif [ "$PROTOCOL" = thrift ]
then
	ln -s Makefile.thrift.inc src/Makefile.protocol.inc
else
	echo PROTOCOL should be http or grpc or thrift
	exit 5
fi

rm -rf src/plugin
ln -s $PWD/$PLUGIN_DIR src/plugin

pushd src
make 
popd


