EXTRA_LIBS=segment/ucsb/libseg.a -lopencv_features2d -lopencv_imgproc -lopencv_imgcodecs -lopencv_core -lopencv_hal
EXTRA_SOURCES=cass.cpp

DONKEY_HOME=../..
include $(DONKEY_HOME)/src/Makefile.common
